<?php
namespace Apcap_data\Repositories;

use Core\data\SuperRepository;

/**
 * TipoBemRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TipoBemRepository extends SuperRepository
{
}
