<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'Apcap_mobile\Module'                        => __DIR__ . '/Module.php',
    'Apcap_mobile\Controller\SkeletonController' => __DIR__ . '/src/Apcap_mobile/Controller/SkeletonController.php',
    'Apcap_mobileTest\Framework\TestCase'        => __DIR__ . '/tests/Apcap_mobile/Framework/TestCase.php',
    'Apcap_mobileTest\SampleTest'                => __DIR__ . '/tests/Apcap_mobile/SampleTest.php',
);
