<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'Apcap_security\Module'                        => __DIR__ . '/Module.php',
    'Apcap_security\Controller\SkeletonController' => __DIR__ . '/src/Apcap_security/Controller/SkeletonController.php',
    'Apcap_securityTest\Framework\TestCase'        => __DIR__ . '/tests/Apcap_security/Framework/TestCase.php',
    'Apcap_securityTest\SampleTest'                => __DIR__ . '/tests/Apcap_security/SampleTest.php',
);
