<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'Apcac_idist_motoboy\Module'                        => __DIR__ . '/Module.php',
    'Apcac_idist_motoboy\Controller\SkeletonController' => __DIR__ . '/src/Apcac_idist_motoboy/Controller/SkeletonController.php',
    'Apcac_idist_motoboyTest\Framework\TestCase'        => __DIR__ . '/tests/Apcac_idist_motoboy/Framework/TestCase.php',
    'Apcac_idist_motoboyTest\SampleTest'                => __DIR__ . '/tests/Apcac_idist_motoboy/SampleTest.php',
);
