<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'Apcap_data\Module'                        => __DIR__ . '/Module.php',
    'Apcap_data\Controller\TesteController' => __DIR__ . '/src/Apcap_data/Controller/TesteController.php',
    'Apcap_dataTest\Framework\TestCase'        => __DIR__ . '/tests/Apcap_data/Framework/TestCase.php',
    'Apcap_dataTest\SampleTest'                => __DIR__ . '/tests/Apcap_data/SampleTest.php',
);
